eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
server:
  error:
    include-exception: false
spring:
  kafka:
    bootstrap-servers: broker:29092
  mvc:
    problemdetails:
      enabled: false
  datasource:
    password: postgres
    url: jdbc:postgresql://db-orders:5432/orders
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      enabled: false
management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 10s